"""
Project 9: Automated Report Emailer
Author: mikey811
Description: Builds an HTML summary report from a SQLite database or CSV,
             attaches the Project 7 Excel dashboard, and sends it via SMTP
             (Gmail / any SMTP relay). Designed to run as a cron job or
             GitHub Actions scheduled workflow.
"""

import os
import smtplib
import sqlite3
import argparse
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from pathlib import Path

import pandas as pd

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# CONFIG (override via env vars or CLI)
# ---------------------------------------------------------------------------
SMTP_HOST     = os.getenv("SMTP_HOST",     "smtp.gmail.com")
SMTP_PORT     = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER     = os.getenv("SMTP_USER",     "")   # set in env / .env file
SMTP_PASS     = os.getenv("SMTP_PASS",     "")   # App Password for Gmail
REPORT_DB     = os.getenv("REPORT_DB",     "report.db")


# ---------------------------------------------------------------------------
# DEMO DATA SEED
# ---------------------------------------------------------------------------

def seed_demo_db(db_path: str):
    """Create a sample SQLite database if it doesn't exist."""
    if Path(db_path).exists():
        return
    conn = sqlite3.connect(db_path)
    conn.execute("""
        CREATE TABLE IF NOT EXISTS daily_kpis (
            report_date TEXT,
            region      TEXT,
            revenue     REAL,
            orders      INTEGER,
            avg_order   REAL
        )
    """)
    sample_rows = [
        ("2024-07-01", "Northeast",  45200.0, 312, 144.87),
        ("2024-07-01", "Southeast",  31800.0, 241, 131.95),
        ("2024-07-01", "Midwest",    28400.0, 198, 143.43),
        ("2024-07-02", "Northeast",  47900.0, 331, 144.71),
        ("2024-07-02", "Southeast",  33200.0, 258, 128.68),
        ("2024-07-02", "Midwest",    26100.0, 182, 143.41),
    ]
    conn.executemany(
        "INSERT INTO daily_kpis VALUES (?,?,?,?,?)", sample_rows
    )
    conn.commit()
    conn.close()
    log.info("Seeded demo database: %s", db_path)


# ---------------------------------------------------------------------------
# REPORT BUILDER
# ---------------------------------------------------------------------------

def load_kpis(db_path: str, table: str = "daily_kpis") -> pd.DataFrame:
    conn = sqlite3.connect(db_path)
    df = pd.read_sql_query(f"SELECT * FROM {table} ORDER BY report_date DESC", conn)
    conn.close()
    return df


def build_html_report(df: pd.DataFrame, title: str = "Daily KPI Report") -> str:
    """Generate a styled HTML email body from a DataFrame."""
    run_ts  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    total_rev = df["revenue"].sum() if "revenue" in df.columns else "N/A"
    total_ord = df["orders"].sum()  if "orders"  in df.columns else "N/A"

    table_html = df.to_html(
        index=False,
        border=0,
        classes="data-table",
        float_format="{:,.2f}".format,
    )

    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body        {{ font-family: Arial, sans-serif; color: #333; }}
        h1          {{ color: #1F4E79; }}
        .summary    {{ background: #D6E4F0; padding: 12px; border-radius: 6px; margin-bottom: 16px; }}
        .data-table {{ border-collapse: collapse; width: 100%; }}
        .data-table th {{ background: #1F4E79; color: #fff; padding: 8px 12px; text-align: left; }}
        .data-table td {{ padding: 7px 12px; border-bottom: 1px solid #ddd; }}
        .data-table tr:nth-child(even) {{ background: #f2f8fd; }}
        .footer     {{ font-size: 11px; color: #999; margin-top: 24px; }}
      </style>
    </head>
    <body>
      <h1>{title}</h1>
      <div class="summary">
        <strong>Generated:</strong> {run_ts}<br>
        <strong>Total Revenue:</strong> ${total_rev:,.2f}<br>
        <strong>Total Orders:</strong> {total_ord:,}
      </div>
      {table_html}
      <p class="footer">Auto-generated by the Automated Report Emailer &mdash; Project 9</p>
    </body>
    </html>
    """
    return html


# ---------------------------------------------------------------------------
# EMAIL BUILDER + SENDER
# ---------------------------------------------------------------------------

def build_email(
    sender: str,
    recipients: list[str],
    subject: str,
    html_body: str,
    attachment_paths: list[str] = None,
) -> MIMEMultipart:
    msg = MIMEMultipart("mixed")
    msg["From"]    = sender
    msg["To"]      = ", ".join(recipients)
    msg["Subject"] = subject

    # HTML body
    alt = MIMEMultipart("alternative")
    alt.attach(MIMEText(html_body, "html"))
    msg.attach(alt)

    # Attachments
    for path in (attachment_paths or []):
        p = Path(path)
        if not p.exists():
            log.warning("Attachment not found, skipping: %s", path)
            continue
        with open(p, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f"attachment; filename={p.name}",
        )
        msg.attach(part)
        log.info("Attached: %s", p.name)

    return msg


def send_email(
    msg: MIMEMultipart,
    smtp_host: str,
    smtp_port: int,
    smtp_user: str,
    smtp_pass: str,
    dry_run: bool = False,
):
    if dry_run:
        log.info("[DRY RUN] Would send email to: %s", msg["To"])
        log.info("[DRY RUN] Subject: %s", msg["Subject"])
        return

    with smtplib.SMTP(smtp_host, smtp_port) as server:
        server.ehlo()
        server.starttls()
        server.login(smtp_user, smtp_pass)
        server.sendmail(
            msg["From"],
            msg["To"].split(", "),
            msg.as_string(),
        )
    log.info("Email sent successfully to: %s", msg["To"])


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Automated report emailer")
    parser.add_argument("--to",       nargs="+", default=["recipient@example.com"],
                        help="Recipient email addresses")
    parser.add_argument("--subject",  default=f"Daily KPI Report {datetime.now().strftime('%Y-%m-%d')}")
    parser.add_argument("--db",       default=REPORT_DB,    help="Source SQLite database")
    parser.add_argument("--attach",   nargs="*", default=[], help="Extra file paths to attach")
    parser.add_argument("--dry-run",  action="store_true",  help="Build email but do not send")
    parser.add_argument("--smtp-user",default=SMTP_USER)
    parser.add_argument("--smtp-pass",default=SMTP_PASS)
    args = parser.parse_args()

    # Seed demo data
    seed_demo_db(args.db)

    # Build report
    df      = load_kpis(args.db)
    html    = build_html_report(df)
    sender  = args.smtp_user or "noreply@example.com"

    msg = build_email(
        sender=sender,
        recipients=args.to,
        subject=args.subject,
        html_body=html,
        attachment_paths=args.attach,
    )

    send_email(
        msg,
        smtp_host=SMTP_HOST,
        smtp_port=SMTP_PORT,
        smtp_user=args.smtp_user,
        smtp_pass=args.smtp_pass,
        dry_run=args.dry_run,
    )


if __name__ == "__main__":
    main()
